apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST"
      manageAlerts: true
    secureJsonData:
      httpHeaderValue1: "Bearer <token>"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "traceID"
          matcherRegex: "traceID=(\\w+)"
          url: "http://tempo:16686/trace/$${__value.raw}"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:16686
    jsonData:
      httpMethod: "GET"
      serviceMap:
        datasourceUid: "prometheus" 